"""Export-only Reporter adapter; there is intentionally no submit operation."""

from __future__ import annotations

from bountyhunter.models import Finding, Platform, Target

PLATFORM_SECTION_LABELS: dict[Platform, tuple[str, str, str]] = {
    Platform.HACKERONE: ("Summary", "Steps to reproduce", "Impact"),
    Platform.BUGCROWD: ("Overview", "Proof of concept", "Security impact"),
    Platform.INTIGRITI: ("Summary", "Steps to reproduce", "Impact"),
    Platform.IMMUNEFI: ("Bug description", "Reproduction", "Impact"),
    Platform.YESWEHACK: ("Description", "Reproduction steps", "Impact"),
    Platform.SYNACK: ("Summary", "Reproduction", "Impact"),
    Platform.CUSTOM: ("Summary", "Reproduction", "Impact"),
}


class ReporterAdapter:
    """Render platform-shaped Markdown for operator review and export."""

    @staticmethod
    def reproduction(finding: Finding) -> str:
        return _render_reproduction(finding)

    def render(self, target: Target, finding: Finding) -> str:
        verification_note = self.reproduction(finding)
        return self.render_narrative(
            target,
            finding,
            summary=finding.summary,
            impact="Confirm impact manually and update this section before exporting.",
            verification_note=verification_note,
        )

    def render_narrative(
        self,
        target: Target,
        finding: Finding,
        *,
        summary: str,
        impact: str,
        verification_note: str,
    ) -> str:
        summary_label, reproduction_label, impact_label = PLATFORM_SECTION_LABELS[target.platform]
        return (
            f"# {finding.title}\n\n"
            f"**Platform:** {target.platform.value}\n\n"
            f"**Target:** {target.name}\n\n"
            f"**Severity:** {finding.severity.value}\n\n"
            f"## {summary_label}\n\n"
            f"{summary}\n\n"
            f"## {reproduction_label}\n\n"
            f"{verification_note}\n\n"
            f"## {impact_label}\n\n"
            f"{impact}\n\n"
            "---\n"
            "Draft generated by Bounty Hunter. Review and submit manually.\n"
        )


def _render_reproduction(finding: Finding) -> str:
    if not finding.reproduction_steps:
        return (
            "Reproduction steps are not yet verified. Add the operator-verified steps before "
            "exporting. No automated submission is performed."
        )
    return "\n".join(
        f"{index}. {step}" for index, step in enumerate(finding.reproduction_steps, start=1)
    )
